import { Container } from '@mui/material';
import CircularProgress from '@mui/material/CircularProgress';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';

interface Article {
  id: number;
  key_word_id: number;
  title: string;
  published: string;
  link: string;
  posted: boolean;
  created_at: string;
  updated_at: string;
  category_label: string;
  score: number;
  score_second: null | number;
  key_word: {
    key_word: string;
  };
}

interface RelatedKeywords {
  [key: string]: number;
}

interface APIResponse {
  article: Article;
  related_keywords: RelatedKeywords;
  array_keywords: number;
  text: string;
}

const AlertArticle: React.FC = () => {
  const params = useParams();
  const [errorMessage, setErrorMessage] = useState<boolean>(false);
  const { id } = params;
  const [article, setArticle] = useState<Article | null>(null);
  const [relatedKeywords, setRelatedKeywords] =
    useState<RelatedKeywords | null>(null);
  const [arrayKeywords, setArrayKeywords] = useState<number>(0);
  const [text, setText] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchArticle = async () => {
      try {
        const response = await fetch(
          `https://new-alerts-e4f6j5kdsq-ew.a.run.app/articles/${id}`
        );
        const data: APIResponse = await response.json();
        setArticle(data.article);
        setRelatedKeywords(data.related_keywords);
        setArrayKeywords(data.array_keywords);
        setText(data.text);
        setLoading(false);
      } catch (error) {
        console.error(error);
        setErrorMessage(true);
        setLoading(false)
      }
    };

    fetchArticle();
  }, [id]);
  if (loading) {
    return (
      <>
        <Paper
          sx={{
            width: '80%',
            backgroundColor: 'gray',
            overflow: 'hidden',
            marginLeft: '10%',
          }}
        >
          <div className="container_loading">
            <div className="loading_text">
              <p>
                May take a few seconds waiting for Chat GPT to analyze the
                article
              </p>
            </div>
            <div className="loading_indicator">
              <CircularProgress />
            </div>
          </div>
        </Paper>
      </>
    );
  }
  if (errorMessage) {
    return (
      <>
        <Paper
          sx={{
            width: '80%',
            backgroundColor: 'gray',
            overflow: 'hidden',
            marginLeft: '10%',
          }}
        >
          <div className="container_loading">
            <div className="loading_text">
              <p>You reached your free limit in Open AI</p>
            </div>
          </div>
        </Paper>
      </>
    );
  }

  return (
    <div>
      <Paper
        sx={{
          width: '80%',
          backgroundColor: 'gray',
          overflow: 'hidden',
          marginLeft: '10%',
        }}
      >
        <div className="padding_vertical_big"></div>
        <Container sx={{ backgroundColor: 'white' }}>
          {relatedKeywords && (
            <div style={{ padding: '5rem' }}>
              <Typography variant="h5">Related Keywords:</Typography>
              <div className="padding_vertical_small"></div>
              {Object.entries(relatedKeywords).map(([keyword, value]) => {
                if (value > 0) {
                  return (
                    <Typography key={keyword}>
                      <strong>Keyword: </strong>
                      {keyword} <br />
                      <strong>number of key words:</strong> {value}
                    </Typography>
                  );
                }
                return null;
              })}
              <Typography>Array Keywords Score: {arrayKeywords}</Typography>
              <div className="padding_vertical_big"></div>
              <h4>Generated by Chat gpt</h4>
              <Typography variant="body1">{text}</Typography>
              <div className="padding_vertical_big"></div>
            </div>
          )}
        </Container>
        <div className="padding_vertical_big"></div>
      </Paper>
    </div>
  );
};

export default AlertArticle;
